FORMAT: 1A
HOST: https://dataiq.leadiq.com

# LeadIQ Contact Search

This GraphQL API is designed to find a contact by name and company or linkedin url. A state-of-the-art technology is used to support tracking original data sources for email, phone and job changes. Contact Search is available starting October 2018 and new end points like account search (searched all contacts in one account) and data feedback will be provided in Q4 2018.

| Features Supported |         Release Date          |
|--------------------|-------------------------------|
| **Contact Search** | October 2018                  |
| **Account Search** | Q4 2018                       |
| **Data Feeback**   | Q4 2018                       |

**Note**
This documentation is to describe how to use the API and explain some of the design decisions. Tools like Insomnia or GraphQL Playground are privided as a more interactive way to explore GraphQL schema. For details, please see [Using GraphQL](#using-graphql).


# Authentication

Authentication token must be sent in the request header.

The **access token** can be requested at api-support at leadiq.com.

|    HTTP Header    |              Header Value             |
|-------------------|---------------------------------------|
| **Content-Type**  | _application/json_                    |
| **Authorization** | _Bearer <your_access_token>_ |

## Search by Name and Company [/api/graphql{?name_company}]

Find a contact by name and company.

**Request Body**

```
query SearchPeople($input: SearchPeopleInput!) {
    searchPeople(input: $input) {
        totalResults
        hasMore
        results {
            id
            name {
                first
                middle
                last
            }
            personalEmails {
                value
            }
            linkedin {
                linkedinUrl
                linkedinId
            }
            currentPositions {
                title
                company {
                    name
                    industry
                }
                emails {
                    value
                    meta {
                        sources {
                            source
                        }
                    }
                }
                phones {
                    value
                    meta {
                        sources {
                            source
                        }
                    }
                }
            }
        }
    }
}

Query Variables

{
    "input": {
        "fullName": "Niels Bentzen",
        "company": {
            "name": "Danish Refugee Council"
        }
    }
}
```

### Request [POST]

Gives back a list of users based on the search input - name and company.


+ Request (application/json)

    + Header 
            
            Authorization: Bearer your_access_token

    + Attributes (SearchPeopleInput)

    + Body

            {
                "query": "query SearchPeople($input: SearchPeopleInput!) { searchPeople(input: $input) { totalResults hasMore results { id name { first last } linkedin { linkedinUrl linkedinId } currentPositions { title company { name industry } emails { value type meta { sources { source } } } phones { value type meta { sources { source } } } } } } }",
                "variables": {"input": { "fullName": "Niels Bentzen", "company":{ "name": "Danish Refugee Council" }}}
            }
            

+ Response 200 (application/json)

    + Attributes (SearchResult)

    + Body

            {
                "data": {
                    "searchPeople": {
                        "hasMore": false,
                        "results": [
                            {
                                "currentPositions": [
                                    {
                                        "company": {
                                            "industry": "Nonprofit Organization Management",
                                            "name": "Danish Refugee Council / Dansk Flygtningehjælp"
                                        },
                                        "emails": [
                                            {
                                                "meta": {
                                                    "sources": [
                                                        {
                                                            "source": "leadiq-own-lc"
                                                        }
                                                    ]
                                                },
                                                "value": "niels.bentzen@drc.dk"
                                            }
                                        ],
                                        "phones": [],
                                        "title": "Program Advisor"
                                    }
                                ],
                                "id": "a936b80a-14b2-4323-981b-cbc9d8c86972",
                                "linkedin": {
                                    "linkedinId": "84546029",
                                    "linkedinUrl": "https://www.linkedin.com/in/niels-bentzen-12539324"
                                },
                                "name": {
                                    "first": "Niels",
                                    "last": "Bentzen",
                                    "middle": null
                                },
                                "personalEmails": []
                            }
                        ],
                        "totalResults": 1
                    }
                }
            }            

+ Response 400 (application/json)
    
    + Body

            {
                "errors": [
                    {
                        "message": "error message"
                    }
                ]
            }

+ Response 401 (application/json)

    + Body

            {
                "errors": [
                    {
                        "message": "error message"
                    }
                ]
            }

## Search by Name and Domain [/api/graphql{?name_domain}]

Find a contact by name and domain.

**Request Body**

```
query SearchPeople($input: SearchPeopleInput!) {
    searchPeople(input: $input) {
        totalResults
        hasMore
        results {
            id
            name {
                first
                middle
                last
            }
            personalEmails {
                value
            }
            linkedin {
                linkedinUrl
                linkedinId
            }
            currentPositions {
                title
                company {
                    name
                    industry
                }
                emails {
                    value
                    meta {
                        sources {
                            source
                        }
                    }
                }
                phones {
                    value
                    meta {
                        sources {
                            source
                        }
                    }
                }
            }
        }
    }
}

Query Variables

{
    "input": {
        "fullName": "Melissa Schwenker"
        "company": {
            "domain": "salesforce.com"
        }
    }
}
```

### Request [POST]

Gives back a list of users based on the search input - name and domain.

+ Request (application/json)

    + Header 
            
            Authorization: Bearer your_access_token

    + Attributes (SearchPeopleInput)

    + Body

            {
                "query": "query SearchPeople($input: SearchPeopleInput!) { searchPeople(input: $input) { totalResults hasMore results { id name { first last } linkedin { linkedinUrl linkedinId } currentPositions { title company { name industry } emails { value type meta { sources { source } } } phones { value type meta { sources { source } } } } } } }",
                "variables": {"input": { "fullName": "Melissa Schwenker", "company":{ "domain": "salesforce.com" }}}
            }
            

+ Response 200 (application/json)

    + Attributes (SearchResult)

    + Body

            {
                "data": {
                    "searchPeople": {
                        "hasMore": false,
                        "results": [
                            {
                                "currentPositions": [
                                    {
                                        "company": {
                                            "industry": "Internet",
                                            "name": "Salesforce"
                                        },
                                        "emails": [
                                            {
                                                "meta": {
                                                    "sources": [
                                                        {
                                                            "source": "leadiq-own-unknown"
                                                        },
                                                        {
                                                            "source": "leadiq-vendor-em"
                                                        },
                                                        {
                                                            "source": "leadiq-vendor-sg"
                                                        },
                                                        {
                                                            "source": "leadiq-own-lc"
                                                        }
                                                    ]
                                                },
                                                "value": "mschwenker@salesforce.com"
                                            }
                                        ],
                                        "phones": [
                                            {
                                                "meta": {
                                                    "sources": [
                                                        {
                                                            "source": "leadiq-vendor-em"
                                                        }
                                                    ]
                                                },
                                                "value": "+1-312-288-3600"
                                            },
                                            {
                                                "meta": {
                                                    "sources": [
                                                        {
                                                            "source": "leadiq-vendor-em"
                                                        }
                                                    ]
                                                },
                                                "value": "+1-312-873-0640"
                                            },
                                            {
                                                "meta": {
                                                    "sources": [
                                                        {
                                                            "source": "leadiq-vendor-sg"
                                                        }
                                                    ]
                                                },
                                                "value": "+1-415-901-7000"
                                            }
                                        ],
                                        "title": "Commercial Account Executive - Financial Services "
                                    }
                                ],
                                "id": "0187781a-40f4-42b0-807a-0df874e9b841",
                                "linkedin": {
                                    "linkedinId": "17840808",
                                    "linkedinUrl": "https://www.linkedin.com/in/melissa-schwenker-660b845"
                                },
                                "name": {
                                    "first": "Melissa",
                                    "last": "Schwenker",
                                    "middle": null
                                },
                                "personalEmails": []
                            }
                        ],
                        "totalResults": 1
                    }
                },
                "extensions": {
                    "cost": {
                        "emailCost": 1,
                        "phoneCost": 3,
                        "total": 4
                    }
                }
            }       

+ Response 400 (application/json)
    
    + Body

            {
                "errors": [
                    {
                        "message": "error message"
                    }
                ]
            }

+ Response 401 (application/json)

    + Body

            {
                "errors": [
                    {
                        "message": "error message"
                    }
                ]
            }

## Search by Linkedin Url [/api/graphql{?linkedinUrl}]

Find a contact by linkedin url. 

**Refs**:
1. Current version still requires you to pass in first name. This will be fixed in the next release.
2. Linkedin url can't have the ending slash. This will be fixed in the next release.

**Request Body**

```
Query Variables

{
    "input": {
        "linkedinUrl": "/in/niels-bentzen-12539324/",
        "containsWorkContactInfo": false
    }
}
```

### Request [POST]

Gives back a list of users based on the search input - linkedin url.

+ Request (application/json)

    + Header 
            
            Authorization: Bearer your_access_token

    + Attributes (SearchPeopleInput)

    + Body

            {
                "query": "query SearchPeople($input: SearchPeopleInput!) { searchPeople(input: $input) { totalResults hasMore results { id name { first last } linkedin { linkedinUrl linkedinId } currentPositions { title company { name industry } emails { value type meta { sources { source } } } phones { value type meta { sources { source } } } } } } }",
                "variables": {"input": { "linkedinUrl": "/in/niels-bentzen-12539324/", "containsWorkContactInfo": false }}
            }

+ Response 200 (application/json)

    + Attributes (SearchResult)

    + Body

            {
                "data": {
                    "searchPeople": {
                        "hasMore": false,
                        "results": [
                            {
                                "currentPositions": [
                                    {
                                        "company": {
                                            "domain": "drc.dk",
                                            "emailDomains": null,
                                            "industry": "Nonprofit Organization Management",
                                            "name": "Danish Refugee Council / Dansk Flygtningehjælp"
                                        },
                                        "emails": [
                                            {
                                                "meta": {
                                                    "sources": [
                                                        {
                                                            "source": "leadiq-own-lc"
                                                        }
                                                    ]
                                                },
                                                "value": "niels.bentzen@drc.dk"
                                            }
                                        ],
                                        "phones": [],
                                        "title": "Program Advisor"
                                    }
                                ],
                                "id": "a936b80a-14b2-4323-981b-cbc9d8c86972",
                                "linkedin": {
                                    "linkedinId": "84546029",
                                    "linkedinUrl": "https://www.linkedin.com/in/niels-bentzen-12539324",
                                    "meta": {
                                        "sources": [
                                            {
                                                "source": "lc_data"
                                            }
                                        ]
                                    }
                                },
                                "name": {
                                    "first": "Niels",
                                    "last": "Bentzen",
                                    "middle": null
                                },
                                "personalEmails": []
                            }
                        ],
                        "totalResults": 1
                    }
                },
                "extensions": {
                    "cost": {
                        "emailCost": 1,
                        "phoneCost": 0,
                        "total": 1
                    }
                }
            }

+ Response 400 (application/json)
    
    + Body

            {
                "errors": [
                    {
                        "message": "error message"
                    }
                ]
            }

+ Response 401 (application/json)

    + Body

            {
                "errors": [
                    {
                        "message": "error message"
                    }
                ]
            }

# Data Structures

## SearchPeopleInput
+ skip (number)
+ limit (number)
+ firstName (required, string)
+ lastName (string)
+ middleName (string)
+ fullName (string)
+ company (CompanyDetails)
+ linkedinId (string)
+ linkedinUrl (string)
+ email (string)
+ containsWorkContactInfo (boolean)

## CompanyDetails
+ name (string)
+ domain (string)
+ linkedinId (string)
+ country (string)

## PersonRecord
+ id (required, string)
+ name (required, NameInfo)
+ version (required, number)
+ currentPositions (required, array[PositionRecord])
+ pastPositions (required, array[PositionRecord])
+ personalEmails (required, array[EmailRecord])
+ phones (required, array[PhoneRecord])
+ linkedin (LinkedinRecord)

## NameInfo
+ first (required, string)
+ fullName (required, string)
+ last (string)
+ middle (string)

## PositionRecord
+ companyId (required, string)
+ company (FlatCompanyForResponse)
+ title (string)
+ dateRange (DateRange)
+ emails (required, array[EmailRecord])
+ phones (required, array[PhoneRecord])
+ meta (MetaRecord_PositionType_GenericStatusType)

## FlatCompanyForResponse
+ name (required, string)
+ alternativeNames (array[string])
+ domain (string)
+ emailDomains (array[string])
+ type (string)
+ phones (array[string])
+ country (string)
+ address (string)
+ locationInfo (LocationInfo)
+ logoUrl (string)
+ numberOfEmployees (number)

## LocationInfo
+ formattedAddress (string)
+ street1 (string)
+ street2 (string)
+ city (string)
+ areaLevel1 (string)
+ country (string)
+ postalCode (string)

## DateRange
+ start (number) - Timestamp
+ end (number) - Timestamp

## `MetaRecord_PositionType_GenericStatusType`
+ sources (required, SourceType_PositionType_GenericStatusType)
+ lastUpdated (required, number) - Timestamp

## `SourceType_PositionType_GenericStatusType`
+ source (required, string)
+ type (required, PositionType)
+ status (required, GenericStatusType)
+ otherDetails (required, SourceDetails)

## PositionType (enum[string])
+ Current
+ Past

## GenericStatusType (enum[string])
+ Valid
+ Invalid

## SourceDetails
+ providerIds (required, array[string])

## EmailRecord
+ value (required, string)
+ type (required, EmailType)
+ status (required, EmailVerificationStatus)
+ meta (required, MetaRecord_EmailType_EmailVerificationStatusType)

## EmailType (enum[string])
+ WorkEmail
+ PersonalEmail

## EmailVerificationStatus
+ type (required, EmailVerificationStatusType)
+ lastSeen (required, number) - Timestamp

## EmailVerificationStatusType (enum[string])
+ Verified
+ Unverified
+ VerifiedLikely
+ Invalid

## `MetaRecord_EmailType_EmailVerificationStatusType`
+ sources (required, array[SourceType_EmailType_EmailVerificationStatusType])
+ lastUpdated (required, number) - Timestamp

## `SourceType_EmailType_EmailVerificationStatusType`
+ source (required, string)
+ type (required, EmailType)
+ status (required, EmailVerificationStatusType)
+ otherDetails (required, SourceDetails)

## PhoneRecord
+ value (required, string)
+ type (required, PhoneType)
+ meta (required, MetaRecord_PhoneType_GenericStatusType)

## PhoneType (enum[string])
+ WorkPhone
+ PersonalLandline
+ PersonalMobile
+ WorkMobile
+ WorkHQ
+ PersonalPhone
+ WorkBranch

## `MetaRecord_PhoneType_GenericStatusType`
+ sources (required, array[SourceType_PhoneType_GenericStatusType])
+ lastUpdated (required, number) - Timestamp

## `SourceType_PhoneType_GenericStatusType`
+ source (required, string)
+ type (required, PhoneType)
+ status (required, GenericStatusType)
+ otherDetails (required, SourceDetails)

## LinkedinRecord
+ linkedinId (string)
+ linkedinUrl (string)
+ type (required, LinkedinType)
+ meta (required, MetaRecord_LinkedinType_GenericStatusType)

## LinkedinType (enum[string])
+ NotApplicable

## `MetaRecord_LinkedinType_GenericStatusType`
+ sources (required, array[SourceType_LinkedinType_GenericStatusType])
+ lastUpdated (required, number) - Timestamp

## `SourceType_LinkedinType_GenericStatusType`
+ source (required, string)
+ type (required, LinkedinType)
+ status (required, GenericStatusType)
+ otherDetails (required, SourceDetails)

## SearchResult
+ totalResults (required, number)
+ hasMore (required, boolean)
+ results (required, PersonRecord)


# Group Using GraphQL
<a name="using-graphql"></a>

GraphQL is a web technology used to decouple the request/response structure from particular endpoints.
It works by acting as a layer over existing request/response systems (most frequently HTTP) that allows the client to specify the type and structure of data that they wish to receive. 

The server manages efficiently receiving queries and aggregating the requisite data for the client.

## Getting Started

Working with GraphQL is fairly simply however it can be somewhat unusual for people are coming from REST backgrounds. It should seem more familiar to those who have dealt with Databases in the past as it is simply a query language for client requests.

To use GraphQL you need to know what types are available to the client for requests. For REST endpoints this is quite static, as the endpoints are developed by the API server and then exposed for consumption. Meaning that changing the data requires the server bumps up new API version. For GraphQL, this is only the case if there are *brand-new* types being introduced, otherwise you can compose the existing types in any manner you please.

To see the support types in the LeadIQ GraphQL API you could try reading the schema using tools like Insomnia or GraphQL Playground.

## Resources
GraphQL as a technology is far too large to elaborate completely here. For more technical references on how to use GraphQL itself please review the following resources.

- [GraphQL Docs](http://graphql.org/learn/)

Here is the list of tools that you can download to explore GraphQL schema.

- [Insomnia](https://insomnia.rest/graphql/)
- [GraphQL Playground](https://github.com/prisma/graphql-playground)